name: beerstory
description: Save your favorite beers and find them back instantly !
version: 2.0.2+10
publish_to: none
repository: https://github.com/Skyost/Beerstory

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.2.0
  intl: any
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  uuid: ^4.5.1
  flutter_riverpod: ^3.0.3
  openfoodfacts: ^3.27.0
  http: ^1.5.0
  lottie: ^3.3.2
  flutter_native_splash: ^2.4.7
  jovial_svg: ^1.1.28
  mobile_scanner: ^7.1.3
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  forui: ^0.16.0
  forui_assets: ^0.16.0
  slang: ^4.9.2
  slang_flutter: ^4.9.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  file_picker: ^10.3.3
  package_info_plus: ^9.0.0
  sentry_flutter: ^9.7.0

dev_dependencies:
  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.7.1
  custom_lint: ^0.8.0
  riverpod_lint: ^3.0.3
  release: ^0.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/fonts/
    - assets/images/
  fonts:
    - family: BirdsOfParadise
      fonts:
        - asset: assets/fonts/BirdsOfParadise.ttf

release:
  changelog:
    header: '# ðŸ“° Beerstory Changelog'
    defaultIgnoredTypes: ['test', 'ci']

flutter_native_splash:
  color: "#009688"
  image: assets/splash/default.png
  fullscreen: true
  android_12:
    image: assets/splash/android12.png
